INSERT INTO STUDENT (ID, FIRSTNAME, LASTNAME, EMAIL) VALUES (2, 'GIMMY', 'ROBY', 'GIMMY@GMAIL.COM');
INSERT INTO STUDENT (ID, FIRSTNAME, LASTNAME, EMAIL) VALUES (3, 'JOHN', 'ROBY', 'JOHN@GMAIL.COM');
INSERT INTO STUDENT (ID, FIRSTNAME, LASTNAME, EMAIL) VALUES (4, 'MICHELLE', 'ROBY', 'MICHELLE@GMAIL.COM');
INSERT INTO STUDENT (ID, FIRSTNAME, LASTNAME, EMAIL) VALUES (5, 'RONALD', 'ROBY', 'RONALD@GMAIL.COM');